version: '2'
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    volumes:
      - ./config.yaml:/etc/config.yaml
    networks:
      - envoy
    expose:
      - "80"
      - "8001"
    ports:
      - "61892:8000"
      - "61893:8001"
  
  auth-service:
    image: quay.io/datawire/kat-backend:10
    environment:
    - DEBUG=1
    networks:
      envoy:
        aliases:
          - envoy
    expose:
      - "8080"
    ports:
      - "61898:8080"

networks:
  envoy: {}
