---
apiVersion: v1
kind: Service
metadata:
  name: retry
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: retry_mapping
      prefix: /retry/
      service: retry
      retry_policy:
        retry_on: "5xx"
        num_retries: 3
        per_try_timeout: "500ms"
      ambassador_id: 017-retry
spec:
  selector:
    app: retry
  ports:
  - port: 3000
    name: http
    targetPort: http
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: retry
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: retry
    spec:
      containers:
      - name: retry
        image: agervais/ambassador-retry-service:1.0.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
