static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          add_user_agent: true
          idle_timeout: 0.840s
          stat_prefix: ingress_http
          use_remote_address: true
          route_config:
            name: local_route
            virtual_hosts:
            - name: grpc_echo
              domains: ["*"]
              routes:
              - match:
                  prefix: /
                route:
                  cluster: grpc_echo
              cors:
                allow_origin:
                - "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web
                max_age: "1728000"
                expose_headers: grpc-status,grpc-message
                enabled: true
          http_filters:
          - name: envoy.grpc_web
            config: {}
          - name: envoy.cors
            config: {}
          - name: envoy.router
            config: {}

  clusters:
  - name: grpc_echo
    connect_timeout: 1s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address: grpc_echo
        port_value: 8080

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 61893

# static_resources:
#   listeners:
#   - name: listener_0
#     address:
#       socket_address: { address: 0.0.0.0, port_value: 8080 }
#     filter_chains:
#     - filters:
#       - name: envoy.http_connection_manager
#         config:
#           codec_type: auto
#           stat_prefix: ingress_http
#           route_config:
#             name: local_route
#             virtual_hosts:
#             - name: local_service
#               domains: ["*"]
#               routes:
#               - match:
#                   prefix: "/”
#                 route:
#                   cluster: auth_service
#               cors:
#                 allow_origin:
#                 - "*"
#                 allow_methods: GET, PUT, DELETE, POST, OPTIONS
#                 allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web
#                 max_age: "1728000"
#                 expose_headers: grpc-status,grpc-message
#                 enabled: true
#           http_filters:
#           - name: envoy.grpc_web
#           - name: envoy.cors
#           - name: envoy.router
#   clusters:
#   - name: auth_service
#     connect_timeout: 0.25s
#     type: logical_dns
#     http2_protocol_options: {}
#     lb_policy: round_robin
#     hosts:
# socket_address:
#   address: auth-server
#   port_value: 9090