##############################################################################
# Ambassador-specific granular commands and utilities                        #
##############################################################################

version: 2.1

executors:

  "oss-linux":
    machine:
      # If you bump this, be sure to bump it in the "aes-linux"
      # executor below, and to bump "install-python.executor-key" in
      # the "oss-linux-setup" and "aes-linux-setup" commands below.
      image: "ubuntu-2004:202008-01"
    working_directory: ~/project/ambassador

  "aes-linux":
    machine:
      # If you bump this, be sure to bump it in the "oss-linux"
      # executor above, and to bump "install-python.executor-key" in
      # the "oss-linux-setup" and "aes-linux-setup" commands below.
      image: "ubuntu-2004:202008-01"
    working_directory: ~/project

commands:

  "oss-linux-setup":
    steps:
      - install-python:
          executor-key: "202008-01"
      - pip-install:
          packages: awscli packaging
      - install-go
      - install-kubectl
      - oss-checkout

  "aes-linux-setup":
    steps:
      - install-python:
          executor-key: "202008-01"
      - pip-install:
          packages: awscli packaging
      - install-go
      - install-kubectl
      - install-node
      - checkout

  "oss-checkout":
    steps:
      - when:
          condition:
            or:
            - equal: [ "https://github.com/datawire/ambassador", << pipeline.project.git_url >> ]
            - equal: [ "https://github.com/datawire/ambassador-private", << pipeline.project.git_url >> ]
          steps:
            - checkout:
                path: ~/project/ambassador
      - when:
          condition:
            or:
            - equal: [ "https://github.com/datawire/apro", << pipeline.project.git_url >> ]
            - equal: [ "https://github.com/datawire/apro-private", << pipeline.project.git_url >> ]
          steps:
            - run:
                working_directory: ~/project
                command: rmdir ~/project/ambassador
            - checkout:
                path: ~/project

  "aes-save-logs":
    steps:
      - run:
          name: "Gather logs"
          when: always
          command: |
            rsync -ma --include='*/' --include='*.tap' --include='*.log' --include='Test*.webm' --exclude='*' . /tmp/test-logs
      - store_artifacts:
          name: "Store logs"
          path: /tmp/test-logs
          destination: test-logs
