version: 2.1

jobs:
  "oss-generate":
    executor: oss-linux
    steps:
      - job-generate

  "oss-lint":
    executor: oss-linux
    steps:
      - job-lint

  "oss-images":
    parameters:
      "release":
        type: boolean
        default: false
    executor: oss-linux
    steps:
      - amb-linux-install
      - amb-checkout
      - skip-if-only-changes:
          to: docs/
      - oss-images-build-and-test
      - when:
          condition: << parameters.release >>
          steps:
            - run:
                name: "Release"
                command: |
                  docker login -u="${DOCKER_RELEASE_USERNAME}" -p="${DOCKER_RELEASE_PASSWORD}" "${RELEASE_REGISTRY%%/*}"
                  DEV_KUBECONFIG="-skip-for-release-" make release/bits

  "oss-promote-to-rc-latest":
    executor: oss-linux
    steps:
      - job-promote-to-rc-latest:
          channel: oss

  "oss-promote-to-ga":
    executor: oss-linux
    steps:
      - job-promote-to-ga:
          channel: oss

workflows:
  # All of these filters assume that "Only build pull requests" is turned on at
  # https://app.circleci.com/settings/project/github/datawire/apro/advanced
  #
  # It is important that the same job name not appear in multiple
  # workflows; otherwise their GitHub statuses will stomp on
  # eachother.
  "OSS: Dev":
    # Run this workflow on just 'master' and PRs.
    jobs:
      - "oss-images":
          name: "oss-dev-images"
      - "oss-generate":
          name: "oss-dev-generate"
      - "oss-lint":
          name: "oss-dev-lint"
  "OSS: Release":
    when:
      or:
      - equal: [ "https://github.com/datawire/ambassador", << pipeline.project.git_url >> ]
      - equal: [ "https://github.com/datawire/ambassador-private", << pipeline.project.git_url >> ]
    # Run this workflow on tags, not branches or PRs.
    jobs:
      - "oss-images":
          name: "oss-release-images"
          release: true
          # Run this on just prerelease tags
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+-(rc|ea)\.[0-9]+$/
            branches:
              ignore: /.*/
      - "oss-promote-to-rc-latest":
          name: "oss-release-promote-to-rc-latest"
          requires:
          - "oss-release-images"
          # Run this on just RC tags
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$/
            branches:
              ignore: /.*/
      - "oss-promote-to-ga":
          name: "oss-release-promote-to-ga"
          # Run this on just GA tags
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
