version: 2.1

# Secure environment variables set from the Web UI:
# - NETLIFY_AUTH_TOKEN (Netlify)
# - GH_TOKEN (GitHub)

_anchors:
  "website-job": &website-job
    machine:
      # If you bump this, be sure to bump "install-python.executor-key"
      # in the "website-setup" command below.
      image: "ubuntu-1604:201903-01"
    working_directory: ~/project/ambassador

commands:

  "website-setup":
    steps:
      - install-node:
          version: "11"
      - install-python:
          executor-key: "201903-01"
          version: "3.7.0"
      - run:
          name: "Show environment"
          command: |
            env | grep -e GIT -e TRAVIS -e CIRCLE | sort
      - oss-checkout

jobs:

  "website-preview-build":
    <<: *website-job
    steps:
      - website-setup
      - run: ./.ci/website-preview-build
      - persist_to_workspace:
          root: /tmp/getambassador.io
          paths:
            - public

  "website-preview-publish":
    <<: *website-job
    steps:
      - website-setup
      - attach_workspace:
          at: /tmp/getambassador.io
      - run: ./.ci/website-preview-publish

  "website-preview-blc":
    <<: *website-job
    steps:
      - website-setup
      - attach_workspace:
          at: /tmp/getambassador.io
      - run: ./.ci/website-preview-blc

  "website-prod-publish":
    <<: *website-job
    steps:
      - website-setup
      - run: ./.ci/website-prod-publish

workflows:
  # All of these filters assume that "Only build pull requests" is turned on at
  # https://app.circleci.com/settings/project/github/datawire/apro/advanced
  # and that any non-'master' branches that we wish to run on are set up to be
  # triggered by GitHub actions (see ".github/workflows/circleci-branches.yml").
  "Docs: Dev":
    jobs:
      - "website-preview-build":
          filters:
            # Run this on prerelease tags (in addition to 'master' and
            # PRs) so that we have a preview for the smoke-testers to use.
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+-.*/
      - "website-preview-publish":
          requires: ["website-preview-build"]
          filters:
            # Run this on prerelease tags (in addition to PRs) so that
            # we have a preview for the smoke-testers to use.
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+-.*/
            # And don't bother running on 'master'.
            branches:
              ignore:
                - master
                - /^release\/v1\.[0-9]+$/
      - "website-preview-blc":
          requires: ["website-preview-build"]
          # Just run this on 'master' and on PRs; don't bother with
          # prerelease tags; we already check those trees for broken
          # links from the PR.
  "Docs: Release":
    when:
      equal: [ "https://github.com/datawire/ambassador", << pipeline.project.git_url >> ]
    jobs:
      - "website-prod-publish":
          filters:
            branches:
              only:
                - master
                - /^release\/v1\.[0-9]+$/
