version: 2.1

# Secure environment variables set from the Web UI:
# - NETLIFY_AUTH_TOKEN (Netlify)
# - GH_TOKEN (GitHub)

_anchors:
  "website-job": &website-job
    machine:
      # If you bump this, be sure to bump "install-python.executor-key"
      # in the "website-setup" command below.
      image: "ubuntu-1604:201903-01"
    working_directory: ~/project/ambassador

commands:

  "website-setup":
    steps:
      - install-node:
          version: "11"
      - install-python:
          executor-key: "201903-01"
          version: "3.7.0"
      - run:
          name: "Show environment"
          command: |
            env | grep -e GIT -e TRAVIS -e CIRCLE | sort
      - oss-checkout

jobs:

  "website-main":
    <<: *website-job
    steps:
      - website-setup
      - run: ./.ci/website-preview-build
      - run: ./.ci/website-preview-publish
      - run: ./.ci/website-preview-blc

workflows:
  # All of these filters assume that "Only build pull requests" is turned on at
  # https://app.circleci.com/settings/project/github/datawire/apro/advanced
  "Docs":
    jobs:
      - "website-main":
          # Run this on prerelease tags (in addition to 'master' and PRs)
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+-.*/
