static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          add_user_agent: true
          idle_timeout: 0.840s
          stat_prefix: egress_http
          use_remote_address: true
          route_config:
            name: local_route
            virtual_hosts:
            - name: grpc_echo
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/echo.EchoService/Echo"
                route:
                  cluster: grpc_echo
                  prefix_rewrite: "echo.EchoService/Echo"
          http_filters:
          - name: envoy.grpc_http1_bridge
            config: {}
          - name: envoy.router
            config: {}
  
  clusters:
  - name: grpc_echo
    connect_timeout: 1s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address: grpc_echo
        port_value: 8080

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 61893
