version: '2'
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    volumes:
      - ./config.yaml:/etc/config.yaml
    networks:
      - envoy
    expose:
      - "80"
      - "8001"
    ports:
      - "61892:8000"
      - "61893:8001"

  grpc_echo:
    image: quay.io/datawire/kat-backend:11
    environment:
    - DEBUG=1
    - KAT_BACKEND_TYPE=grpc_echo
    networks:
      envoy:
        aliases:
          - envoy
    expose:
      - "8080"

networks:
  envoy: {}
