version: '2'
services:

  # curl -v -H "requested-cookie: foo, bar, baz" -H "requested-status:307"  http://localhost:61880/echo-service/get  
  # ambassador:
  #   image: quay.io/datawire/ambassador:0.51.2
  #   ports:
  #   - 61880:80
  #   volumes:
  #   - ./config:/ambassador/ambassador-config
  #   environment:
  #   - AMBASSADOR_NO_KUBEWATCH=no_kubewatch
  #   networks:
  #   - ambassador

  # curl -v -H "requested-cookie: foo, bar, baz" -H "requested-status:307"  http://localhost:61592/echo-service/get
  envoy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    volumes:
      - ./config.yaml:/etc/config.yaml
    networks:
      - ambassador
    ports:
      - "61592:8000"
      - "61593:8001"
  
  # curl -v -H "requested-cookie: foo, bar, baz" -H "requested-status:307"  http://localhost:61594/echo-service/get
  # curl -v -H "requested-status:200" -H "x-grpc-auth-append: foo=bar; baz=bar" -H "foo: foo" http://localhost:61592/headers
  auth-service:
    image: quay.io/datawire/kat-backend:11
    environment:
    - DEBUG=1
    - BACKEND=true
    - KAT_BACKEND_TYPE=grpc_auth
    networks:
      ambassador:
        aliases:
          - ambassador
    expose:
      - "8080"
    ports:
      - "61594:8080"

  echo-service:
    image: kennethreitz/httpbin:latest
    networks:
      ambassador:
        aliases:
          - ambassador
    expose:
      - "80"
    ports:
      - "61595:80"

networks:
  ambassador: {}
